#!/usr/bin/env ruby
$stage = nil
$level = 0
$concepts = []
$skin = nil

def stage(name)
  $stage = name
  $level = 0
  $concepts = []
  $skin = nil
end

def concepts(*items)
  $concepts = items
end

def skin(name)
  $skin = name
end

def level(uri)
  $level += 1
  level_id = uri.gsub(/.*org\/games\/\d+\/levels\/(\d+)/, "\\1")
  puts "#{$stage}\t#{$concepts.join(',')}\t#{level_id}\t"
end

Dir.glob('*.script').each do |script|
  $stdout.reopen("#{script}.csv", "w")
  puts("Stage  Concepts  LevelID")
  load script
end
